### ISSUE TITLE
Any plans to upgrade to 1.19?

### ISSUE THREAD

**Issue by Laisky** [edgelesssys/ertgo#1]
Are there any plans to upgrade ego to support Go 1.19 or even further to 1.20?

If not, could you provide some upgrade guidelines so I can learn how to upgrade to 1.19?

It would be a great help to me.
Thank you!

**Comment by thomasten** [comment]
Yes, we update to newer Go versions on occasion. There's no ETA yet for the next update.

For customers who need recent Go versions timely, we can provide this via [enterprise support](https://www.edgeless.systems/enterprise-support/) on demand.

**Comment by thomasten** [comment]
@Laisky EGo v1.2 features Go 1.20
